apiVersion: v1
kind: Service
metadata:
  name: landmark-app-lb
  namespace: production
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-0e6715f30679eb528, subnet-0eaa9b8fef5b49830"
spec:
  type: LoadBalancer
  selector:
    app: landmark-app
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
